// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IMProtocol.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_IMProtocol_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_IMProtocol_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_IMProtocol_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_IMProtocol_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[8]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_IMProtocol_2eproto;
namespace Proto {
class Message;
class MessageDefaultTypeInternal;
extern MessageDefaultTypeInternal _Message_default_instance_;
class Request;
class RequestDefaultTypeInternal;
extern RequestDefaultTypeInternal _Request_default_instance_;
class Request_login;
class Request_loginDefaultTypeInternal;
extern Request_loginDefaultTypeInternal _Request_login_default_instance_;
class Request_logout;
class Request_logoutDefaultTypeInternal;
extern Request_logoutDefaultTypeInternal _Request_logout_default_instance_;
class Request_sendmsg;
class Request_sendmsgDefaultTypeInternal;
extern Request_sendmsgDefaultTypeInternal _Request_sendmsg_default_instance_;
class Response;
class ResponseDefaultTypeInternal;
extern ResponseDefaultTypeInternal _Response_default_instance_;
class Response_login;
class Response_loginDefaultTypeInternal;
extern Response_loginDefaultTypeInternal _Response_login_default_instance_;
class Response_sendmsg;
class Response_sendmsgDefaultTypeInternal;
extern Response_sendmsgDefaultTypeInternal _Response_sendmsg_default_instance_;
}  // namespace Proto
PROTOBUF_NAMESPACE_OPEN
template<> ::Proto::Message* Arena::CreateMaybeMessage<::Proto::Message>(Arena*);
template<> ::Proto::Request* Arena::CreateMaybeMessage<::Proto::Request>(Arena*);
template<> ::Proto::Request_login* Arena::CreateMaybeMessage<::Proto::Request_login>(Arena*);
template<> ::Proto::Request_logout* Arena::CreateMaybeMessage<::Proto::Request_logout>(Arena*);
template<> ::Proto::Request_sendmsg* Arena::CreateMaybeMessage<::Proto::Request_sendmsg>(Arena*);
template<> ::Proto::Response* Arena::CreateMaybeMessage<::Proto::Response>(Arena*);
template<> ::Proto::Response_login* Arena::CreateMaybeMessage<::Proto::Response_login>(Arena*);
template<> ::Proto::Response_sendmsg* Arena::CreateMaybeMessage<::Proto::Response_sendmsg>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Proto {

enum Request_Type : int {
  Request_Type_LOGIN = 0,
  Request_Type_LOGOUT = 1,
  Request_Type_SENDMSG = 2,
  Request_Type_Request_Type_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  Request_Type_Request_Type_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool Request_Type_IsValid(int value);
constexpr Request_Type Request_Type_Type_MIN = Request_Type_LOGIN;
constexpr Request_Type Request_Type_Type_MAX = Request_Type_SENDMSG;
constexpr int Request_Type_Type_ARRAYSIZE = Request_Type_Type_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Request_Type_descriptor();
template<typename T>
inline const std::string& Request_Type_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Request_Type>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Request_Type_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Request_Type_descriptor(), enum_t_value);
}
inline bool Request_Type_Parse(
    const std::string& name, Request_Type* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Request_Type>(
    Request_Type_descriptor(), name, value);
}
enum Response_Type : int {
  Response_Type_LOGIN = 0,
  Response_Type_LOGOUT = 1,
  Response_Type_SENDMSG = 2,
  Response_Type_MESSAGE = 3,
  Response_Type_Response_Type_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  Response_Type_Response_Type_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool Response_Type_IsValid(int value);
constexpr Response_Type Response_Type_Type_MIN = Response_Type_LOGIN;
constexpr Response_Type Response_Type_Type_MAX = Response_Type_MESSAGE;
constexpr int Response_Type_Type_ARRAYSIZE = Response_Type_Type_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Response_Type_descriptor();
template<typename T>
inline const std::string& Response_Type_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Response_Type>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Response_Type_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Response_Type_descriptor(), enum_t_value);
}
inline bool Response_Type_Parse(
    const std::string& name, Response_Type* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Response_Type>(
    Response_Type_descriptor(), name, value);
}
enum Response_login_STAT : int {
  Response_login_STAT_SUCCESS = 0,
  Response_login_STAT_ACCOUNT_NULL = 1,
  Response_login_STAT_ACCOUNT_LOCK = 2,
  Response_login_STAT_PASSWORD_ERROR = 3,
  Response_login_STAT_ERROR = 10,
  Response_login_STAT_Response_login_STAT_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  Response_login_STAT_Response_login_STAT_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool Response_login_STAT_IsValid(int value);
constexpr Response_login_STAT Response_login_STAT_STAT_MIN = Response_login_STAT_SUCCESS;
constexpr Response_login_STAT Response_login_STAT_STAT_MAX = Response_login_STAT_ERROR;
constexpr int Response_login_STAT_STAT_ARRAYSIZE = Response_login_STAT_STAT_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Response_login_STAT_descriptor();
template<typename T>
inline const std::string& Response_login_STAT_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Response_login_STAT>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Response_login_STAT_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Response_login_STAT_descriptor(), enum_t_value);
}
inline bool Response_login_STAT_Parse(
    const std::string& name, Response_login_STAT* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Response_login_STAT>(
    Response_login_STAT_descriptor(), name, value);
}
// ===================================================================

class Request :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Proto.Request) */ {
 public:
  Request();
  virtual ~Request();

  Request(const Request& from);
  Request(Request&& from) noexcept
    : Request() {
    *this = ::std::move(from);
  }

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline Request& operator=(Request&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Request& default_instance();

  enum PduCase {
    kRequestLogin = 11,
    kRequestLogout = 12,
    kRequestSendmsg = 13,
    PDU_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Request* internal_default_instance() {
    return reinterpret_cast<const Request*>(
               &_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Request* other);
  friend void swap(Request& a, Request& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Request* New() const final {
    return CreateMaybeMessage<Request>(nullptr);
  }

  Request* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Request>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Request& from);
  void MergeFrom(const Request& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Request* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.Request";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_IMProtocol_2eproto);
    return ::descriptor_table_IMProtocol_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Request_Type Type;
  static constexpr Type LOGIN =
    Request_Type_LOGIN;
  static constexpr Type LOGOUT =
    Request_Type_LOGOUT;
  static constexpr Type SENDMSG =
    Request_Type_SENDMSG;
  static inline bool Type_IsValid(int value) {
    return Request_Type_IsValid(value);
  }
  static constexpr Type Type_MIN =
    Request_Type_Type_MIN;
  static constexpr Type Type_MAX =
    Request_Type_Type_MAX;
  static constexpr int Type_ARRAYSIZE =
    Request_Type_Type_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Type_descriptor() {
    return Request_Type_descriptor();
  }
  template<typename T>
  static inline const std::string& Type_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Type>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Type_Name.");
    return Request_Type_Name(enum_t_value);
  }
  static inline bool Type_Parse(const std::string& name,
      Type* value) {
    return Request_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // .Proto.Request.Type type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::Proto::Request_Type type() const;
  void set_type(::Proto::Request_Type value);

  // .Proto.Request_login request_login = 11;
  bool has_request_login() const;
  void clear_request_login();
  static const int kRequestLoginFieldNumber = 11;
  const ::Proto::Request_login& request_login() const;
  ::Proto::Request_login* release_request_login();
  ::Proto::Request_login* mutable_request_login();
  void set_allocated_request_login(::Proto::Request_login* request_login);

  // .Proto.Request_logout request_logout = 12;
  bool has_request_logout() const;
  void clear_request_logout();
  static const int kRequestLogoutFieldNumber = 12;
  const ::Proto::Request_logout& request_logout() const;
  ::Proto::Request_logout* release_request_logout();
  ::Proto::Request_logout* mutable_request_logout();
  void set_allocated_request_logout(::Proto::Request_logout* request_logout);

  // .Proto.Request_sendmsg request_sendmsg = 13;
  bool has_request_sendmsg() const;
  void clear_request_sendmsg();
  static const int kRequestSendmsgFieldNumber = 13;
  const ::Proto::Request_sendmsg& request_sendmsg() const;
  ::Proto::Request_sendmsg* release_request_sendmsg();
  ::Proto::Request_sendmsg* mutable_request_sendmsg();
  void set_allocated_request_sendmsg(::Proto::Request_sendmsg* request_sendmsg);

  void clear_pdu();
  PduCase pdu_case() const;
  // @@protoc_insertion_point(class_scope:Proto.Request)
 private:
  class HasBitSetters;
  void set_has_request_login();
  void set_has_request_logout();
  void set_has_request_sendmsg();

  inline bool has_pdu() const;
  inline void clear_has_pdu();

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  int type_;
  union PduUnion {
    PduUnion() {}
    ::Proto::Request_login* request_login_;
    ::Proto::Request_logout* request_logout_;
    ::Proto::Request_sendmsg* request_sendmsg_;
  } pdu_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_IMProtocol_2eproto;
};
// -------------------------------------------------------------------

class Response :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Proto.Response) */ {
 public:
  Response();
  virtual ~Response();

  Response(const Response& from);
  Response(Response&& from) noexcept
    : Response() {
    *this = ::std::move(from);
  }

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline Response& operator=(Response&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Response& default_instance();

  enum PduCase {
    kResponseLogin = 11,
    kResponseSendmsg = 13,
    kMsg = 14,
    PDU_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Response* internal_default_instance() {
    return reinterpret_cast<const Response*>(
               &_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Response* other);
  friend void swap(Response& a, Response& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Response* New() const final {
    return CreateMaybeMessage<Response>(nullptr);
  }

  Response* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Response>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Response& from);
  void MergeFrom(const Response& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Response* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.Response";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_IMProtocol_2eproto);
    return ::descriptor_table_IMProtocol_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Response_Type Type;
  static constexpr Type LOGIN =
    Response_Type_LOGIN;
  static constexpr Type LOGOUT =
    Response_Type_LOGOUT;
  static constexpr Type SENDMSG =
    Response_Type_SENDMSG;
  static constexpr Type MESSAGE =
    Response_Type_MESSAGE;
  static inline bool Type_IsValid(int value) {
    return Response_Type_IsValid(value);
  }
  static constexpr Type Type_MIN =
    Response_Type_Type_MIN;
  static constexpr Type Type_MAX =
    Response_Type_Type_MAX;
  static constexpr int Type_ARRAYSIZE =
    Response_Type_Type_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Type_descriptor() {
    return Response_Type_descriptor();
  }
  template<typename T>
  static inline const std::string& Type_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Type>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Type_Name.");
    return Response_Type_Name(enum_t_value);
  }
  static inline bool Type_Parse(const std::string& name,
      Type* value) {
    return Response_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // .Proto.Response.Type type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::Proto::Response_Type type() const;
  void set_type(::Proto::Response_Type value);

  // .Proto.Response_login response_login = 11;
  bool has_response_login() const;
  void clear_response_login();
  static const int kResponseLoginFieldNumber = 11;
  const ::Proto::Response_login& response_login() const;
  ::Proto::Response_login* release_response_login();
  ::Proto::Response_login* mutable_response_login();
  void set_allocated_response_login(::Proto::Response_login* response_login);

  // .Proto.Response_sendmsg response_sendmsg = 13;
  bool has_response_sendmsg() const;
  void clear_response_sendmsg();
  static const int kResponseSendmsgFieldNumber = 13;
  const ::Proto::Response_sendmsg& response_sendmsg() const;
  ::Proto::Response_sendmsg* release_response_sendmsg();
  ::Proto::Response_sendmsg* mutable_response_sendmsg();
  void set_allocated_response_sendmsg(::Proto::Response_sendmsg* response_sendmsg);

  // .Proto.Message msg = 14;
  bool has_msg() const;
  void clear_msg();
  static const int kMsgFieldNumber = 14;
  const ::Proto::Message& msg() const;
  ::Proto::Message* release_msg();
  ::Proto::Message* mutable_msg();
  void set_allocated_msg(::Proto::Message* msg);

  void clear_pdu();
  PduCase pdu_case() const;
  // @@protoc_insertion_point(class_scope:Proto.Response)
 private:
  class HasBitSetters;
  void set_has_response_login();
  void set_has_response_sendmsg();
  void set_has_msg();

  inline bool has_pdu() const;
  inline void clear_has_pdu();

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  int type_;
  union PduUnion {
    PduUnion() {}
    ::Proto::Response_login* response_login_;
    ::Proto::Response_sendmsg* response_sendmsg_;
    ::Proto::Message* msg_;
  } pdu_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_IMProtocol_2eproto;
};
// -------------------------------------------------------------------

class Request_login :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Proto.Request_login) */ {
 public:
  Request_login();
  virtual ~Request_login();

  Request_login(const Request_login& from);
  Request_login(Request_login&& from) noexcept
    : Request_login() {
    *this = ::std::move(from);
  }

  inline Request_login& operator=(const Request_login& from) {
    CopyFrom(from);
    return *this;
  }
  inline Request_login& operator=(Request_login&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Request_login& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Request_login* internal_default_instance() {
    return reinterpret_cast<const Request_login*>(
               &_Request_login_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(Request_login* other);
  friend void swap(Request_login& a, Request_login& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Request_login* New() const final {
    return CreateMaybeMessage<Request_login>(nullptr);
  }

  Request_login* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Request_login>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Request_login& from);
  void MergeFrom(const Request_login& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Request_login* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.Request_login";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_IMProtocol_2eproto);
    return ::descriptor_table_IMProtocol_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string password = 2;
  void clear_password();
  static const int kPasswordFieldNumber = 2;
  const std::string& password() const;
  void set_password(const std::string& value);
  void set_password(std::string&& value);
  void set_password(const char* value);
  void set_password(const char* value, size_t size);
  std::string* mutable_password();
  std::string* release_password();
  void set_allocated_password(std::string* password);

  // uint64 ID = 1;
  void clear_id();
  static const int kIDFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::uint64 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // @@protoc_insertion_point(class_scope:Proto.Request_login)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
  ::PROTOBUF_NAMESPACE_ID::uint64 id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_IMProtocol_2eproto;
};
// -------------------------------------------------------------------

class Response_login :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Proto.Response_login) */ {
 public:
  Response_login();
  virtual ~Response_login();

  Response_login(const Response_login& from);
  Response_login(Response_login&& from) noexcept
    : Response_login() {
    *this = ::std::move(from);
  }

  inline Response_login& operator=(const Response_login& from) {
    CopyFrom(from);
    return *this;
  }
  inline Response_login& operator=(Response_login&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Response_login& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Response_login* internal_default_instance() {
    return reinterpret_cast<const Response_login*>(
               &_Response_login_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(Response_login* other);
  friend void swap(Response_login& a, Response_login& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Response_login* New() const final {
    return CreateMaybeMessage<Response_login>(nullptr);
  }

  Response_login* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Response_login>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Response_login& from);
  void MergeFrom(const Response_login& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Response_login* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.Response_login";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_IMProtocol_2eproto);
    return ::descriptor_table_IMProtocol_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Response_login_STAT STAT;
  static constexpr STAT SUCCESS =
    Response_login_STAT_SUCCESS;
  static constexpr STAT ACCOUNT_NULL =
    Response_login_STAT_ACCOUNT_NULL;
  static constexpr STAT ACCOUNT_LOCK =
    Response_login_STAT_ACCOUNT_LOCK;
  static constexpr STAT PASSWORD_ERROR =
    Response_login_STAT_PASSWORD_ERROR;
  static constexpr STAT ERROR =
    Response_login_STAT_ERROR;
  static inline bool STAT_IsValid(int value) {
    return Response_login_STAT_IsValid(value);
  }
  static constexpr STAT STAT_MIN =
    Response_login_STAT_STAT_MIN;
  static constexpr STAT STAT_MAX =
    Response_login_STAT_STAT_MAX;
  static constexpr int STAT_ARRAYSIZE =
    Response_login_STAT_STAT_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  STAT_descriptor() {
    return Response_login_STAT_descriptor();
  }
  template<typename T>
  static inline const std::string& STAT_Name(T enum_t_value) {
    static_assert(::std::is_same<T, STAT>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function STAT_Name.");
    return Response_login_STAT_Name(enum_t_value);
  }
  static inline bool STAT_Parse(const std::string& name,
      STAT* value) {
    return Response_login_STAT_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // string friends = 2;
  void clear_friends();
  static const int kFriendsFieldNumber = 2;
  const std::string& friends() const;
  void set_friends(const std::string& value);
  void set_friends(std::string&& value);
  void set_friends(const char* value);
  void set_friends(const char* value, size_t size);
  std::string* mutable_friends();
  std::string* release_friends();
  void set_allocated_friends(std::string* friends);

  // .Proto.Response_login.STAT stat = 1;
  void clear_stat();
  static const int kStatFieldNumber = 1;
  ::Proto::Response_login_STAT stat() const;
  void set_stat(::Proto::Response_login_STAT value);

  // @@protoc_insertion_point(class_scope:Proto.Response_login)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr friends_;
  int stat_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_IMProtocol_2eproto;
};
// -------------------------------------------------------------------

class Request_logout :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Proto.Request_logout) */ {
 public:
  Request_logout();
  virtual ~Request_logout();

  Request_logout(const Request_logout& from);
  Request_logout(Request_logout&& from) noexcept
    : Request_logout() {
    *this = ::std::move(from);
  }

  inline Request_logout& operator=(const Request_logout& from) {
    CopyFrom(from);
    return *this;
  }
  inline Request_logout& operator=(Request_logout&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Request_logout& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Request_logout* internal_default_instance() {
    return reinterpret_cast<const Request_logout*>(
               &_Request_logout_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(Request_logout* other);
  friend void swap(Request_logout& a, Request_logout& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Request_logout* New() const final {
    return CreateMaybeMessage<Request_logout>(nullptr);
  }

  Request_logout* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Request_logout>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Request_logout& from);
  void MergeFrom(const Request_logout& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Request_logout* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.Request_logout";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_IMProtocol_2eproto);
    return ::descriptor_table_IMProtocol_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 ID = 1;
  void clear_id();
  static const int kIDFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::uint64 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // @@protoc_insertion_point(class_scope:Proto.Request_logout)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::uint64 id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_IMProtocol_2eproto;
};
// -------------------------------------------------------------------

class Request_sendmsg :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Proto.Request_sendmsg) */ {
 public:
  Request_sendmsg();
  virtual ~Request_sendmsg();

  Request_sendmsg(const Request_sendmsg& from);
  Request_sendmsg(Request_sendmsg&& from) noexcept
    : Request_sendmsg() {
    *this = ::std::move(from);
  }

  inline Request_sendmsg& operator=(const Request_sendmsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline Request_sendmsg& operator=(Request_sendmsg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Request_sendmsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Request_sendmsg* internal_default_instance() {
    return reinterpret_cast<const Request_sendmsg*>(
               &_Request_sendmsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(Request_sendmsg* other);
  friend void swap(Request_sendmsg& a, Request_sendmsg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Request_sendmsg* New() const final {
    return CreateMaybeMessage<Request_sendmsg>(nullptr);
  }

  Request_sendmsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Request_sendmsg>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Request_sendmsg& from);
  void MergeFrom(const Request_sendmsg& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Request_sendmsg* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.Request_sendmsg";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_IMProtocol_2eproto);
    return ::descriptor_table_IMProtocol_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string msg = 4;
  void clear_msg();
  static const int kMsgFieldNumber = 4;
  const std::string& msg() const;
  void set_msg(const std::string& value);
  void set_msg(std::string&& value);
  void set_msg(const char* value);
  void set_msg(const char* value, size_t size);
  std::string* mutable_msg();
  std::string* release_msg();
  void set_allocated_msg(std::string* msg);

  // uint64 ID = 2;
  void clear_id();
  static const int kIDFieldNumber = 2;
  ::PROTOBUF_NAMESPACE_ID::uint64 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // uint64 objID = 3;
  void clear_objid();
  static const int kObjIDFieldNumber = 3;
  ::PROTOBUF_NAMESPACE_ID::uint64 objid() const;
  void set_objid(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // uint32 msgID = 1;
  void clear_msgid();
  static const int kMsgIDFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::uint32 msgid() const;
  void set_msgid(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // @@protoc_insertion_point(class_scope:Proto.Request_sendmsg)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr msg_;
  ::PROTOBUF_NAMESPACE_ID::uint64 id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 objid_;
  ::PROTOBUF_NAMESPACE_ID::uint32 msgid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_IMProtocol_2eproto;
};
// -------------------------------------------------------------------

class Response_sendmsg :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Proto.Response_sendmsg) */ {
 public:
  Response_sendmsg();
  virtual ~Response_sendmsg();

  Response_sendmsg(const Response_sendmsg& from);
  Response_sendmsg(Response_sendmsg&& from) noexcept
    : Response_sendmsg() {
    *this = ::std::move(from);
  }

  inline Response_sendmsg& operator=(const Response_sendmsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline Response_sendmsg& operator=(Response_sendmsg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Response_sendmsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Response_sendmsg* internal_default_instance() {
    return reinterpret_cast<const Response_sendmsg*>(
               &_Response_sendmsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(Response_sendmsg* other);
  friend void swap(Response_sendmsg& a, Response_sendmsg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Response_sendmsg* New() const final {
    return CreateMaybeMessage<Response_sendmsg>(nullptr);
  }

  Response_sendmsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Response_sendmsg>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Response_sendmsg& from);
  void MergeFrom(const Response_sendmsg& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Response_sendmsg* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.Response_sendmsg";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_IMProtocol_2eproto);
    return ::descriptor_table_IMProtocol_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 msgID = 1;
  void clear_msgid();
  static const int kMsgIDFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::uint32 msgid() const;
  void set_msgid(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // bool stat = 2;
  void clear_stat();
  static const int kStatFieldNumber = 2;
  bool stat() const;
  void set_stat(bool value);

  // @@protoc_insertion_point(class_scope:Proto.Response_sendmsg)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::uint32 msgid_;
  bool stat_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_IMProtocol_2eproto;
};
// -------------------------------------------------------------------

class Message :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Proto.Message) */ {
 public:
  Message();
  virtual ~Message();

  Message(const Message& from);
  Message(Message&& from) noexcept
    : Message() {
    *this = ::std::move(from);
  }

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }
  inline Message& operator=(Message&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Message& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Message* internal_default_instance() {
    return reinterpret_cast<const Message*>(
               &_Message_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  void Swap(Message* other);
  friend void swap(Message& a, Message& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Message* New() const final {
    return CreateMaybeMessage<Message>(nullptr);
  }

  Message* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Message>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Message& from);
  void MergeFrom(const Message& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Message* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.Message";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_IMProtocol_2eproto);
    return ::descriptor_table_IMProtocol_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string msg = 3;
  void clear_msg();
  static const int kMsgFieldNumber = 3;
  const std::string& msg() const;
  void set_msg(const std::string& value);
  void set_msg(std::string&& value);
  void set_msg(const char* value);
  void set_msg(const char* value, size_t size);
  std::string* mutable_msg();
  std::string* release_msg();
  void set_allocated_msg(std::string* msg);

  // uint64 fromID = 2;
  void clear_fromid();
  static const int kFromIDFieldNumber = 2;
  ::PROTOBUF_NAMESPACE_ID::uint64 fromid() const;
  void set_fromid(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // @@protoc_insertion_point(class_scope:Proto.Message)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr msg_;
  ::PROTOBUF_NAMESPACE_ID::uint64 fromid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_IMProtocol_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Request

// .Proto.Request.Type type = 1;
inline void Request::clear_type() {
  type_ = 0;
}
inline ::Proto::Request_Type Request::type() const {
  // @@protoc_insertion_point(field_get:Proto.Request.type)
  return static_cast< ::Proto::Request_Type >(type_);
}
inline void Request::set_type(::Proto::Request_Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:Proto.Request.type)
}

// .Proto.Request_login request_login = 11;
inline bool Request::has_request_login() const {
  return pdu_case() == kRequestLogin;
}
inline void Request::set_has_request_login() {
  _oneof_case_[0] = kRequestLogin;
}
inline void Request::clear_request_login() {
  if (has_request_login()) {
    delete pdu_.request_login_;
    clear_has_pdu();
  }
}
inline ::Proto::Request_login* Request::release_request_login() {
  // @@protoc_insertion_point(field_release:Proto.Request.request_login)
  if (has_request_login()) {
    clear_has_pdu();
      ::Proto::Request_login* temp = pdu_.request_login_;
    pdu_.request_login_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Proto::Request_login& Request::request_login() const {
  // @@protoc_insertion_point(field_get:Proto.Request.request_login)
  return has_request_login()
      ? *pdu_.request_login_
      : *reinterpret_cast< ::Proto::Request_login*>(&::Proto::_Request_login_default_instance_);
}
inline ::Proto::Request_login* Request::mutable_request_login() {
  if (!has_request_login()) {
    clear_pdu();
    set_has_request_login();
    pdu_.request_login_ = CreateMaybeMessage< ::Proto::Request_login >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:Proto.Request.request_login)
  return pdu_.request_login_;
}

// .Proto.Request_logout request_logout = 12;
inline bool Request::has_request_logout() const {
  return pdu_case() == kRequestLogout;
}
inline void Request::set_has_request_logout() {
  _oneof_case_[0] = kRequestLogout;
}
inline void Request::clear_request_logout() {
  if (has_request_logout()) {
    delete pdu_.request_logout_;
    clear_has_pdu();
  }
}
inline ::Proto::Request_logout* Request::release_request_logout() {
  // @@protoc_insertion_point(field_release:Proto.Request.request_logout)
  if (has_request_logout()) {
    clear_has_pdu();
      ::Proto::Request_logout* temp = pdu_.request_logout_;
    pdu_.request_logout_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Proto::Request_logout& Request::request_logout() const {
  // @@protoc_insertion_point(field_get:Proto.Request.request_logout)
  return has_request_logout()
      ? *pdu_.request_logout_
      : *reinterpret_cast< ::Proto::Request_logout*>(&::Proto::_Request_logout_default_instance_);
}
inline ::Proto::Request_logout* Request::mutable_request_logout() {
  if (!has_request_logout()) {
    clear_pdu();
    set_has_request_logout();
    pdu_.request_logout_ = CreateMaybeMessage< ::Proto::Request_logout >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:Proto.Request.request_logout)
  return pdu_.request_logout_;
}

// .Proto.Request_sendmsg request_sendmsg = 13;
inline bool Request::has_request_sendmsg() const {
  return pdu_case() == kRequestSendmsg;
}
inline void Request::set_has_request_sendmsg() {
  _oneof_case_[0] = kRequestSendmsg;
}
inline void Request::clear_request_sendmsg() {
  if (has_request_sendmsg()) {
    delete pdu_.request_sendmsg_;
    clear_has_pdu();
  }
}
inline ::Proto::Request_sendmsg* Request::release_request_sendmsg() {
  // @@protoc_insertion_point(field_release:Proto.Request.request_sendmsg)
  if (has_request_sendmsg()) {
    clear_has_pdu();
      ::Proto::Request_sendmsg* temp = pdu_.request_sendmsg_;
    pdu_.request_sendmsg_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Proto::Request_sendmsg& Request::request_sendmsg() const {
  // @@protoc_insertion_point(field_get:Proto.Request.request_sendmsg)
  return has_request_sendmsg()
      ? *pdu_.request_sendmsg_
      : *reinterpret_cast< ::Proto::Request_sendmsg*>(&::Proto::_Request_sendmsg_default_instance_);
}
inline ::Proto::Request_sendmsg* Request::mutable_request_sendmsg() {
  if (!has_request_sendmsg()) {
    clear_pdu();
    set_has_request_sendmsg();
    pdu_.request_sendmsg_ = CreateMaybeMessage< ::Proto::Request_sendmsg >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:Proto.Request.request_sendmsg)
  return pdu_.request_sendmsg_;
}

inline bool Request::has_pdu() const {
  return pdu_case() != PDU_NOT_SET;
}
inline void Request::clear_has_pdu() {
  _oneof_case_[0] = PDU_NOT_SET;
}
inline Request::PduCase Request::pdu_case() const {
  return Request::PduCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// Response

// .Proto.Response.Type type = 1;
inline void Response::clear_type() {
  type_ = 0;
}
inline ::Proto::Response_Type Response::type() const {
  // @@protoc_insertion_point(field_get:Proto.Response.type)
  return static_cast< ::Proto::Response_Type >(type_);
}
inline void Response::set_type(::Proto::Response_Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:Proto.Response.type)
}

// .Proto.Response_login response_login = 11;
inline bool Response::has_response_login() const {
  return pdu_case() == kResponseLogin;
}
inline void Response::set_has_response_login() {
  _oneof_case_[0] = kResponseLogin;
}
inline void Response::clear_response_login() {
  if (has_response_login()) {
    delete pdu_.response_login_;
    clear_has_pdu();
  }
}
inline ::Proto::Response_login* Response::release_response_login() {
  // @@protoc_insertion_point(field_release:Proto.Response.response_login)
  if (has_response_login()) {
    clear_has_pdu();
      ::Proto::Response_login* temp = pdu_.response_login_;
    pdu_.response_login_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Proto::Response_login& Response::response_login() const {
  // @@protoc_insertion_point(field_get:Proto.Response.response_login)
  return has_response_login()
      ? *pdu_.response_login_
      : *reinterpret_cast< ::Proto::Response_login*>(&::Proto::_Response_login_default_instance_);
}
inline ::Proto::Response_login* Response::mutable_response_login() {
  if (!has_response_login()) {
    clear_pdu();
    set_has_response_login();
    pdu_.response_login_ = CreateMaybeMessage< ::Proto::Response_login >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:Proto.Response.response_login)
  return pdu_.response_login_;
}

// .Proto.Response_sendmsg response_sendmsg = 13;
inline bool Response::has_response_sendmsg() const {
  return pdu_case() == kResponseSendmsg;
}
inline void Response::set_has_response_sendmsg() {
  _oneof_case_[0] = kResponseSendmsg;
}
inline void Response::clear_response_sendmsg() {
  if (has_response_sendmsg()) {
    delete pdu_.response_sendmsg_;
    clear_has_pdu();
  }
}
inline ::Proto::Response_sendmsg* Response::release_response_sendmsg() {
  // @@protoc_insertion_point(field_release:Proto.Response.response_sendmsg)
  if (has_response_sendmsg()) {
    clear_has_pdu();
      ::Proto::Response_sendmsg* temp = pdu_.response_sendmsg_;
    pdu_.response_sendmsg_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Proto::Response_sendmsg& Response::response_sendmsg() const {
  // @@protoc_insertion_point(field_get:Proto.Response.response_sendmsg)
  return has_response_sendmsg()
      ? *pdu_.response_sendmsg_
      : *reinterpret_cast< ::Proto::Response_sendmsg*>(&::Proto::_Response_sendmsg_default_instance_);
}
inline ::Proto::Response_sendmsg* Response::mutable_response_sendmsg() {
  if (!has_response_sendmsg()) {
    clear_pdu();
    set_has_response_sendmsg();
    pdu_.response_sendmsg_ = CreateMaybeMessage< ::Proto::Response_sendmsg >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:Proto.Response.response_sendmsg)
  return pdu_.response_sendmsg_;
}

// .Proto.Message msg = 14;
inline bool Response::has_msg() const {
  return pdu_case() == kMsg;
}
inline void Response::set_has_msg() {
  _oneof_case_[0] = kMsg;
}
inline void Response::clear_msg() {
  if (has_msg()) {
    delete pdu_.msg_;
    clear_has_pdu();
  }
}
inline ::Proto::Message* Response::release_msg() {
  // @@protoc_insertion_point(field_release:Proto.Response.msg)
  if (has_msg()) {
    clear_has_pdu();
      ::Proto::Message* temp = pdu_.msg_;
    pdu_.msg_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Proto::Message& Response::msg() const {
  // @@protoc_insertion_point(field_get:Proto.Response.msg)
  return has_msg()
      ? *pdu_.msg_
      : *reinterpret_cast< ::Proto::Message*>(&::Proto::_Message_default_instance_);
}
inline ::Proto::Message* Response::mutable_msg() {
  if (!has_msg()) {
    clear_pdu();
    set_has_msg();
    pdu_.msg_ = CreateMaybeMessage< ::Proto::Message >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:Proto.Response.msg)
  return pdu_.msg_;
}

inline bool Response::has_pdu() const {
  return pdu_case() != PDU_NOT_SET;
}
inline void Response::clear_has_pdu() {
  _oneof_case_[0] = PDU_NOT_SET;
}
inline Response::PduCase Response::pdu_case() const {
  return Response::PduCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// Request_login

// uint64 ID = 1;
inline void Request_login::clear_id() {
  id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Request_login::id() const {
  // @@protoc_insertion_point(field_get:Proto.Request_login.ID)
  return id_;
}
inline void Request_login::set_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:Proto.Request_login.ID)
}

// string password = 2;
inline void Request_login::clear_password() {
  password_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Request_login::password() const {
  // @@protoc_insertion_point(field_get:Proto.Request_login.password)
  return password_.GetNoArena();
}
inline void Request_login::set_password(const std::string& value) {
  
  password_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Proto.Request_login.password)
}
inline void Request_login::set_password(std::string&& value) {
  
  password_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Proto.Request_login.password)
}
inline void Request_login::set_password(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  password_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Proto.Request_login.password)
}
inline void Request_login::set_password(const char* value, size_t size) {
  
  password_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Proto.Request_login.password)
}
inline std::string* Request_login::mutable_password() {
  
  // @@protoc_insertion_point(field_mutable:Proto.Request_login.password)
  return password_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Request_login::release_password() {
  // @@protoc_insertion_point(field_release:Proto.Request_login.password)
  
  return password_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Request_login::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    
  } else {
    
  }
  password_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), password);
  // @@protoc_insertion_point(field_set_allocated:Proto.Request_login.password)
}

// -------------------------------------------------------------------

// Response_login

// .Proto.Response_login.STAT stat = 1;
inline void Response_login::clear_stat() {
  stat_ = 0;
}
inline ::Proto::Response_login_STAT Response_login::stat() const {
  // @@protoc_insertion_point(field_get:Proto.Response_login.stat)
  return static_cast< ::Proto::Response_login_STAT >(stat_);
}
inline void Response_login::set_stat(::Proto::Response_login_STAT value) {
  
  stat_ = value;
  // @@protoc_insertion_point(field_set:Proto.Response_login.stat)
}

// string friends = 2;
inline void Response_login::clear_friends() {
  friends_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Response_login::friends() const {
  // @@protoc_insertion_point(field_get:Proto.Response_login.friends)
  return friends_.GetNoArena();
}
inline void Response_login::set_friends(const std::string& value) {
  
  friends_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Proto.Response_login.friends)
}
inline void Response_login::set_friends(std::string&& value) {
  
  friends_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Proto.Response_login.friends)
}
inline void Response_login::set_friends(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  friends_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Proto.Response_login.friends)
}
inline void Response_login::set_friends(const char* value, size_t size) {
  
  friends_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Proto.Response_login.friends)
}
inline std::string* Response_login::mutable_friends() {
  
  // @@protoc_insertion_point(field_mutable:Proto.Response_login.friends)
  return friends_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Response_login::release_friends() {
  // @@protoc_insertion_point(field_release:Proto.Response_login.friends)
  
  return friends_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Response_login::set_allocated_friends(std::string* friends) {
  if (friends != nullptr) {
    
  } else {
    
  }
  friends_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), friends);
  // @@protoc_insertion_point(field_set_allocated:Proto.Response_login.friends)
}

// -------------------------------------------------------------------

// Request_logout

// uint64 ID = 1;
inline void Request_logout::clear_id() {
  id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Request_logout::id() const {
  // @@protoc_insertion_point(field_get:Proto.Request_logout.ID)
  return id_;
}
inline void Request_logout::set_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:Proto.Request_logout.ID)
}

// -------------------------------------------------------------------

// Request_sendmsg

// uint32 msgID = 1;
inline void Request_sendmsg::clear_msgid() {
  msgid_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Request_sendmsg::msgid() const {
  // @@protoc_insertion_point(field_get:Proto.Request_sendmsg.msgID)
  return msgid_;
}
inline void Request_sendmsg::set_msgid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  msgid_ = value;
  // @@protoc_insertion_point(field_set:Proto.Request_sendmsg.msgID)
}

// uint64 ID = 2;
inline void Request_sendmsg::clear_id() {
  id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Request_sendmsg::id() const {
  // @@protoc_insertion_point(field_get:Proto.Request_sendmsg.ID)
  return id_;
}
inline void Request_sendmsg::set_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:Proto.Request_sendmsg.ID)
}

// uint64 objID = 3;
inline void Request_sendmsg::clear_objid() {
  objid_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Request_sendmsg::objid() const {
  // @@protoc_insertion_point(field_get:Proto.Request_sendmsg.objID)
  return objid_;
}
inline void Request_sendmsg::set_objid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  objid_ = value;
  // @@protoc_insertion_point(field_set:Proto.Request_sendmsg.objID)
}

// string msg = 4;
inline void Request_sendmsg::clear_msg() {
  msg_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Request_sendmsg::msg() const {
  // @@protoc_insertion_point(field_get:Proto.Request_sendmsg.msg)
  return msg_.GetNoArena();
}
inline void Request_sendmsg::set_msg(const std::string& value) {
  
  msg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Proto.Request_sendmsg.msg)
}
inline void Request_sendmsg::set_msg(std::string&& value) {
  
  msg_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Proto.Request_sendmsg.msg)
}
inline void Request_sendmsg::set_msg(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  msg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Proto.Request_sendmsg.msg)
}
inline void Request_sendmsg::set_msg(const char* value, size_t size) {
  
  msg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Proto.Request_sendmsg.msg)
}
inline std::string* Request_sendmsg::mutable_msg() {
  
  // @@protoc_insertion_point(field_mutable:Proto.Request_sendmsg.msg)
  return msg_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Request_sendmsg::release_msg() {
  // @@protoc_insertion_point(field_release:Proto.Request_sendmsg.msg)
  
  return msg_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Request_sendmsg::set_allocated_msg(std::string* msg) {
  if (msg != nullptr) {
    
  } else {
    
  }
  msg_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:Proto.Request_sendmsg.msg)
}

// -------------------------------------------------------------------

// Response_sendmsg

// uint32 msgID = 1;
inline void Response_sendmsg::clear_msgid() {
  msgid_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Response_sendmsg::msgid() const {
  // @@protoc_insertion_point(field_get:Proto.Response_sendmsg.msgID)
  return msgid_;
}
inline void Response_sendmsg::set_msgid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  msgid_ = value;
  // @@protoc_insertion_point(field_set:Proto.Response_sendmsg.msgID)
}

// bool stat = 2;
inline void Response_sendmsg::clear_stat() {
  stat_ = false;
}
inline bool Response_sendmsg::stat() const {
  // @@protoc_insertion_point(field_get:Proto.Response_sendmsg.stat)
  return stat_;
}
inline void Response_sendmsg::set_stat(bool value) {
  
  stat_ = value;
  // @@protoc_insertion_point(field_set:Proto.Response_sendmsg.stat)
}

// -------------------------------------------------------------------

// Message

// uint64 fromID = 2;
inline void Message::clear_fromid() {
  fromid_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Message::fromid() const {
  // @@protoc_insertion_point(field_get:Proto.Message.fromID)
  return fromid_;
}
inline void Message::set_fromid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  fromid_ = value;
  // @@protoc_insertion_point(field_set:Proto.Message.fromID)
}

// string msg = 3;
inline void Message::clear_msg() {
  msg_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Message::msg() const {
  // @@protoc_insertion_point(field_get:Proto.Message.msg)
  return msg_.GetNoArena();
}
inline void Message::set_msg(const std::string& value) {
  
  msg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Proto.Message.msg)
}
inline void Message::set_msg(std::string&& value) {
  
  msg_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Proto.Message.msg)
}
inline void Message::set_msg(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  msg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Proto.Message.msg)
}
inline void Message::set_msg(const char* value, size_t size) {
  
  msg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Proto.Message.msg)
}
inline std::string* Message::mutable_msg() {
  
  // @@protoc_insertion_point(field_mutable:Proto.Message.msg)
  return msg_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Message::release_msg() {
  // @@protoc_insertion_point(field_release:Proto.Message.msg)
  
  return msg_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_msg(std::string* msg) {
  if (msg != nullptr) {
    
  } else {
    
  }
  msg_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:Proto.Message.msg)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Proto

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Proto::Request_Type> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Proto::Request_Type>() {
  return ::Proto::Request_Type_descriptor();
}
template <> struct is_proto_enum< ::Proto::Response_Type> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Proto::Response_Type>() {
  return ::Proto::Response_Type_descriptor();
}
template <> struct is_proto_enum< ::Proto::Response_login_STAT> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Proto::Response_login_STAT>() {
  return ::Proto::Response_login_STAT_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_IMProtocol_2eproto
